name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: RSpec (tests)
    strategy:
      matrix:
        ruby:
          - '2.7.7'
          - '3.0.5'
          - '3.1.3'
          - '3.2.0'

    steps:
    - name: Set up
      uses: ./.github/actions/prelude
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests
      run: bin/rspec

  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop (lint)

    steps:
    - name: Set up
      uses: ./.github/actions/prelude
    - name: Run the rubocop
      run: bin/rubocop

  steep:
    runs-on: ubuntu-latest
    name: Steep (type checks)

    steps:
    - name: Set up
      uses: ./.github/actions/prelude
    - name: Run the steep check
      run: bin/steep check

  rbs:
    runs-on: ubuntu-latest
    name: RBS (type checks)

    steps:
    - name: Set up
      uses: ./.github/actions/prelude
    - name: Run the RBS check
      run: bin/rbs
